name: Create PR for new League Patch

on:
  schedule: [{cron: "0 4 * * *"}]
  workflow_dispatch:

jobs:
  push_to_branch_and_create_pr:
    name: Create PR for new League Patch
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        name: Check out current commit
        
      - id: patch
        name: Get patch info
        uses: marvinscham/get-league-patch@v1
        
      - name: Save patch info to file
        run: echo ${{ steps.patch.outputs.patch }} > .league-patch
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.0.4
        with:
          commit-message: Bump League Patch to ${{ steps.patch.outputs.patch }}
          title: Bump League Patch to ${{ steps.patch.outputs.patch }}
          body: |
            Review criteria:
            
            - [ ] Disenchanter can connect and issue actions
            
            This is an automated PR.
            <sub>[workflow](https://github.com/marvinscham/disenchanter/blob/master/.github/workflows/league-patch.yml).</sub>
          branch: update-league-patch
          labels: documentation, tests needed
          assignees: marvinscham
          reviewers: marvinscham
