name: Add PR for new League Patch

on:
  schedule: [{cron: "0 4 * * *"}]
  workflow_dispatch:

jobs:
  push_to_branch_and_create_pr:
    name: Create PR for new League Patch
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        name: Check out current commit
        
      - name: Create `meta` folder
        run: mkdir -p meta
          
      - name: Get LoL Patch Notes web page
        run: wget -O meta/patch.html https://www.leagueoflegends.com/en-us/news/tags/patch-notes/
          
      - name: Grab latest patch from web page
        run: cat meta/patch.html | sed -n "s/\(Patch [0-9]*\.[0-9]* notes\).*$/\1/p" | sed -n "s/^.*\(Patch [0-9]*\.[0-9]*\).*$/\1/p" > meta/patch.txt
        
      - name: Remove needless webpage file
        run: rm meta/patch.html
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.0.4
        with:
          commit-message: Update League Patch
          title: Update League Patch
          body: |
            This is an automated PR.
            <sub>[workflow](https://github.com/marvinscham/disenchanter/blob/master/.github/workflows/league-patch.yml).</sub>
          branch: update-league-patch
          branch-suffix: "random"
          labels: documentation, tests-needed
